services:
  backend:
    build: ./backend
    container_name: backend-development
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COOKIE_SECRET_KEY=${COOKIE_SECRET_KEY}  
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}

    depends_on:
      - db
    volumes:
      - ~/galaxysurfers-IMS/backend:/usr/src/app
    env_file:
      - ~/galaxysurfers-IMS/backend/.env  # Load backend environment variables
  frontend:
    build: ./frontend 
    container_name: frontend-development
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ~/galaxysurfers-IMS/frontend:/usr/src/app
    env_file:
      - ~/galaxysurfers-IMS/frontend/.env  # Load frontend environment variables
  db:
    image: postgres:latest 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: